apiVersion: v1
kind: Service
metadata:
  name: number-increment-service
spec:
  selector:
    app: number-increment-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-increment-app
spec:
  selector:
    matchLabels:
      app: number-increment-app
  template:
    metadata:
      labels:
        app: number-increment-app
    spec:
      containers:
        - name: number-increment
          image: docker.io/nickimpark/number-increment
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
